# Generated by Django 2.2.7 on 2019-12-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_updaterecord_update_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='updaterecord',
            name='update_mark',
            field=models.CharField(db_column='Mark', max_length=20, null=True),
        ),
    ]
