# Generated by Django 2.2.7 on 2019-12-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daydata',
            name='rst_date',
            field=models.DateField(db_column='date'),
        ),
    ]
